### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'parameters' from Workflow.submit()

### ISSUE THREAD

**Issue by eddie-on-gh** [CermakM/argo-python-sdk#9]
**Describe the bug**
`argo.workflows.dsl._workflow.Workflow.submit` checks if the `Workflow` has an attribute `arguments` but not if that attribute `is not None`. As a result, attempting to invoke `submit()` can result in an `AttributeError` at 
```python
self.spec.arguments.parameters = new_parameters
```

**To Reproduce**
Using the `ArtifactPassing` example,
```python
from argo.workflows.client import V1alpha1Api
from argo.workflows.dsl import Workflow
from argo.workflows.dsl.tasks import artifact, task, V1alpha1Template
from argo.workflows.dsl.templates import template, inputs, outputs, V1alpha1Artifact, V1Container


class ArtifactPassing(Workflow):

    @task
    def generate_artifact(self) -> V1alpha1Template:
        return self.whalesay()

    @task
    @artifact(
        name="message",
        _from="{{tasks.generate-artifact.outputs.artifacts.hello-art}}"
    )
    def consume_artifact(self, message: V1alpha1Artifact) -> V1alpha1Template:
        return self.print_message(message=message)

    @template
    @outputs.artifact(name="hello-art", path="/tmp/hello_world.txt")
    def whalesay(self) -> V1Container:
        container = V1Container(
            name="whalesay",
            image="docker/whalesay:latest",
            command=["sh", "-c"],
            args=["cowsay hello world | tee /tmp/hello_world.txt"]
        )

        return container

    @template
    @inputs.artifact(name="message", path="/tmp/message")
    def print_message(self, message: V1alpha1Artifact) -> V1Container:
        container = V1Container(
            name="print-message",
            image="alpine:latest",
            command=["sh", "-c"],
            args=["cat", "/tmp/message"],
        )

        return container


if __name__ == '__main__':
    argo_api = V1alpha1Api()
    workflow_instance = ArtifactPassing()
    workflow_instance.submit(argo_api, "argo", parameters={"test_param": "some_value"})
```

**Expected behaviour**
The Workflow will be submitted through the API client instead of an AttributeError being raised.

**Screenshots**
N/A

**Additional context**
```
Traceback (most recent call last):
  File ".../artifact-passing.py", line 54, in <module>
    workflow_instance.submit(argo_api, "argo", parameters={"test_param": "some_value"})
  File ".../venv/lib/python3.8/site-packages/argo/workflows/dsl/_workflow.py", line 418, in submit
    self.spec.arguments.parameters = new_parameters
AttributeError: 'NoneType' object has no attribute 'parameters'
```

```bash
$ python
Python 3.8.1 (default, Feb 11 2020, 16:39:15) 
[GCC 7.4.0] on linux
```

It seems to be possible to manually workaround this as so:
```python
        workflow_instance.spec._arguments = argo.workflows.client.V1alpha1Arguments()
        workflow_instance.spec._arguments.parameters = []
```

**Comment by CermakM** [comment]
Hello @Omenien,

This is strange, the `spec.arguments` shouldn't really be `NoneType`... can you please check whether you can reproduce the issue in Python 3.6?

Cheers,
M

**Comment by eddie-on-gh** [comment]
It looks like it's happening for me with Python 3.6 as well.
`python3.6 artifact-passing.py`
```
Traceback (most recent call last):
  File "artifact-passing.py", line 49, in <module>
    workflow_instance.submit(argo_api, "argo", parameters={"test_param": "some_value"})
  File ".../venv2/lib/python3.6/site-packages/argo/workflows/dsl/_workflow.py", line 416, in submit
    self.spec.arguments.parameters = new_parameters
AttributeError: 'NoneType' object has no attribute 'parameters'
```

Here's what's installed into that Python 3.6 environment:
`python3.6 -m pip freeze`
```
argo-workflows==3.0.2
argo-workflows-dsl==0.1.0.dev0
cachetools==4.0.0
certifi==2019.11.28
chardet==3.0.4
google-auth==1.11.2
idna==2.9
inflection==0.3.1
kubernetes==10.0.1
mock==4.0.1
oauthlib==3.1.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
python-dateutil==2.8.1
PyYAML==5.3
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.0
six==1.14.0
urllib3==1.25.8
websocket-client==0.57.0
```
and the specific version of Python 3.6:
```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
```

**Comment by rosscdh** [comment]
+1 same behaviour here.

```
(Pdb) dir(instance.spec.arguments)

['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']

(Pdb) dir(instance.spec.arguments.parameters)
*** AttributeError: 'NoneType' object has no attribute 'parameters'

```

**Comment by rosscdh** [comment]
hacked it on `_workflow.py:416` but it looks like attributes is not being incarnated as V1alpha1Arguments as on line 350 `arguments: V1alpha1Arguments = props.get("arguments")`

props in this case appears to be None.... thus arguments is none



```
            if not self.spec.arguments:
                self.spec.arguments = V1alpha1Arguments(artifacts=[], parameters={})
```

**Comment by CermakM** [comment]
@Omenien just submitted a PR for it, feel free to check it out and let me know :)

The problem here was (and I did not notice it initially, sorry about that), that the Workflow doesn't expect any parameters. You should have the following in the Workflow definition:

```
class ArtifactPassing(Workflow):
    arguments = V1alpha1Arguments(parameters=[V1alpha1Parameter(name="test_param")])
    ...
```

I made some changes so that this case is checked for and an error is raised accordingly, therefore it is more informative for users.

**Comment by CermakM** [comment]
@rosscdh BTW, it's good to have you here, since I don't know how to contact you otherwise... I noticed that you created a package for this already: https://pypi.org/project/argo-workflows-dsl/ which is quite unfortunate for me as I am about to release 0.1 and I cannot use my standard release process for it.

Would you mind giving me ownership of that package so that I could plug it into my release pipeline along with https://pypi.org/project/argo-workflows/?

Cheers,
M

**Comment by rosscdh** [comment]
Hi @CermakM absolutely! sorry I meant to raise it with you! More than happy to release!

**Comment by rosscdh** [comment]
@CermakM I've deleted the PyPi project feel free to take ownership

**Comment by rosscdh** [comment]
fyi https://github.com/pypa/warehouse/issues/7495

**Comment by CermakM** [comment]
Thanks @rosscdh ! We're up with 0.1.0-rc0 https://pypi.org/project/argo-workflows-dsl/0.1.0rc0/ :+1:

**Comment by rosscdh** [comment]
Thanks for this good looking project! made working with the workflows allot simpler
